// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Cliente 1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Cliente 2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Cliente 3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Cliente 4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Cliente 5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Cliente 6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Cliente 7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Cliente 8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Cliente 9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Cliente 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
