// <auto-generated />
using Catalog.PersistenceDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.PersistenceDB.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220222015736_iniatilize")]
    partial class iniatilize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description of product 1",
                            Name = "Product 1",
                            Price = 762m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description of product 2",
                            Name = "Product 2",
                            Price = 299m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description of product 3",
                            Name = "Product 3",
                            Price = 119m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description of product 4",
                            Name = "Product 4",
                            Price = 417m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description of product 5",
                            Name = "Product 5",
                            Price = 226m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description of product 6",
                            Name = "Product 6",
                            Price = 589m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description of product 7",
                            Name = "Product 7",
                            Price = 761m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description of product 8",
                            Name = "Product 8",
                            Price = 696m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description of product 9",
                            Name = "Product 9",
                            Price = 290m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description of product 10",
                            Name = "Product 10",
                            Price = 194m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description of product 11",
                            Name = "Product 11",
                            Price = 160m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description of product 12",
                            Name = "Product 12",
                            Price = 379m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description of product 13",
                            Name = "Product 13",
                            Price = 331m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description of product 14",
                            Name = "Product 14",
                            Price = 744m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description of product 15",
                            Name = "Product 15",
                            Price = 658m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description of product 16",
                            Name = "Product 16",
                            Price = 182m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description of product 17",
                            Name = "Product 17",
                            Price = 836m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description of product 18",
                            Name = "Product 18",
                            Price = 288m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description of product 19",
                            Name = "Product 19",
                            Price = 183m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description of product 20",
                            Name = "Product 20",
                            Price = 364m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description of product 21",
                            Name = "Product 21",
                            Price = 344m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description of product 22",
                            Name = "Product 22",
                            Price = 441m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description of product 23",
                            Name = "Product 23",
                            Price = 198m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description of product 24",
                            Name = "Product 24",
                            Price = 614m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description of product 25",
                            Name = "Product 25",
                            Price = 950m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description of product 26",
                            Name = "Product 26",
                            Price = 351m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description of product 27",
                            Name = "Product 27",
                            Price = 345m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description of product 28",
                            Name = "Product 28",
                            Price = 393m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description of product 29",
                            Name = "Product 29",
                            Price = 887m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description of product 30",
                            Name = "Product 30",
                            Price = 799m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Description of product 31",
                            Name = "Product 31",
                            Price = 924m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Description of product 32",
                            Name = "Product 32",
                            Price = 222m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Description of product 33",
                            Name = "Product 33",
                            Price = 377m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Description of product 34",
                            Name = "Product 34",
                            Price = 336m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Description of product 35",
                            Name = "Product 35",
                            Price = 662m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Description of product 36",
                            Name = "Product 36",
                            Price = 384m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Description of product 37",
                            Name = "Product 37",
                            Price = 306m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Description of product 38",
                            Name = "Product 38",
                            Price = 153m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Description of product 39",
                            Name = "Product 39",
                            Price = 237m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Description of product 40",
                            Name = "Product 40",
                            Price = 412m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Description of product 41",
                            Name = "Product 41",
                            Price = 538m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Description of product 42",
                            Name = "Product 42",
                            Price = 433m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Description of product 43",
                            Name = "Product 43",
                            Price = 288m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Description of product 44",
                            Name = "Product 44",
                            Price = 857m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Description of product 45",
                            Name = "Product 45",
                            Price = 476m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Description of product 46",
                            Name = "Product 46",
                            Price = 561m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Description of product 47",
                            Name = "Product 47",
                            Price = 297m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Description of product 48",
                            Name = "Product 48",
                            Price = 636m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Description of product 49",
                            Name = "Product 49",
                            Price = 109m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Description of product 50",
                            Name = "Product 50",
                            Price = 717m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Description of product 51",
                            Name = "Product 51",
                            Price = 183m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Description of product 52",
                            Name = "Product 52",
                            Price = 742m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Description of product 53",
                            Name = "Product 53",
                            Price = 865m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Description of product 54",
                            Name = "Product 54",
                            Price = 914m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Description of product 55",
                            Name = "Product 55",
                            Price = 978m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Description of product 56",
                            Name = "Product 56",
                            Price = 420m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Description of product 57",
                            Name = "Product 57",
                            Price = 200m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Description of product 58",
                            Name = "Product 58",
                            Price = 505m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Description of product 59",
                            Name = "Product 59",
                            Price = 467m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Description of product 60",
                            Name = "Product 60",
                            Price = 874m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Description of product 61",
                            Name = "Product 61",
                            Price = 344m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Description of product 62",
                            Name = "Product 62",
                            Price = 467m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Description of product 63",
                            Name = "Product 63",
                            Price = 809m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Description of product 64",
                            Name = "Product 64",
                            Price = 490m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Description of product 65",
                            Name = "Product 65",
                            Price = 270m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Description of product 66",
                            Name = "Product 66",
                            Price = 938m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Description of product 67",
                            Name = "Product 67",
                            Price = 101m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Description of product 68",
                            Name = "Product 68",
                            Price = 994m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Description of product 69",
                            Name = "Product 69",
                            Price = 181m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Description of product 70",
                            Name = "Product 70",
                            Price = 373m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Description of product 71",
                            Name = "Product 71",
                            Price = 875m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Description of product 72",
                            Name = "Product 72",
                            Price = 783m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Description of product 73",
                            Name = "Product 73",
                            Price = 150m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Description of product 74",
                            Name = "Product 74",
                            Price = 770m
                        },
                        new
                        {
                            Id = 75,
                            Description = "Description of product 75",
                            Name = "Product 75",
                            Price = 826m
                        },
                        new
                        {
                            Id = 76,
                            Description = "Description of product 76",
                            Name = "Product 76",
                            Price = 911m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Description of product 77",
                            Name = "Product 77",
                            Price = 253m
                        },
                        new
                        {
                            Id = 78,
                            Description = "Description of product 78",
                            Name = "Product 78",
                            Price = 340m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Description of product 79",
                            Name = "Product 79",
                            Price = 237m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Description of product 80",
                            Name = "Product 80",
                            Price = 488m
                        },
                        new
                        {
                            Id = 81,
                            Description = "Description of product 81",
                            Name = "Product 81",
                            Price = 154m
                        },
                        new
                        {
                            Id = 82,
                            Description = "Description of product 82",
                            Name = "Product 82",
                            Price = 709m
                        },
                        new
                        {
                            Id = 83,
                            Description = "Description of product 83",
                            Name = "Product 83",
                            Price = 383m
                        },
                        new
                        {
                            Id = 84,
                            Description = "Description of product 84",
                            Name = "Product 84",
                            Price = 269m
                        },
                        new
                        {
                            Id = 85,
                            Description = "Description of product 85",
                            Name = "Product 85",
                            Price = 716m
                        },
                        new
                        {
                            Id = 86,
                            Description = "Description of product 86",
                            Name = "Product 86",
                            Price = 282m
                        },
                        new
                        {
                            Id = 87,
                            Description = "Description of product 87",
                            Name = "Product 87",
                            Price = 356m
                        },
                        new
                        {
                            Id = 88,
                            Description = "Description of product 88",
                            Name = "Product 88",
                            Price = 462m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Description of product 89",
                            Name = "Product 89",
                            Price = 357m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Description of product 90",
                            Name = "Product 90",
                            Price = 341m
                        },
                        new
                        {
                            Id = 91,
                            Description = "Description of product 91",
                            Name = "Product 91",
                            Price = 283m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Description of product 92",
                            Name = "Product 92",
                            Price = 801m
                        },
                        new
                        {
                            Id = 93,
                            Description = "Description of product 93",
                            Name = "Product 93",
                            Price = 686m
                        },
                        new
                        {
                            Id = 94,
                            Description = "Description of product 94",
                            Name = "Product 94",
                            Price = 363m
                        },
                        new
                        {
                            Id = 95,
                            Description = "Description of product 95",
                            Name = "Product 95",
                            Price = 167m
                        },
                        new
                        {
                            Id = 96,
                            Description = "Description of product 96",
                            Name = "Product 96",
                            Price = 170m
                        },
                        new
                        {
                            Id = 97,
                            Description = "Description of product 97",
                            Name = "Product 97",
                            Price = 623m
                        },
                        new
                        {
                            Id = 98,
                            Description = "Description of product 98",
                            Name = "Product 98",
                            Price = 797m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Description of product 99",
                            Name = "Product 99",
                            Price = 687m
                        },
                        new
                        {
                            Id = 100,
                            Description = "Description of product 100",
                            Name = "Product 100",
                            Price = 538m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductID = 1,
                            Stock = 78
                        },
                        new
                        {
                            Id = 2,
                            ProductID = 2,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            ProductID = 3,
                            Stock = 52
                        },
                        new
                        {
                            Id = 4,
                            ProductID = 4,
                            Stock = 95
                        },
                        new
                        {
                            Id = 5,
                            ProductID = 5,
                            Stock = 74
                        },
                        new
                        {
                            Id = 6,
                            ProductID = 6,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            ProductID = 7,
                            Stock = 89
                        },
                        new
                        {
                            Id = 8,
                            ProductID = 8,
                            Stock = 0
                        },
                        new
                        {
                            Id = 9,
                            ProductID = 9,
                            Stock = 76
                        },
                        new
                        {
                            Id = 10,
                            ProductID = 10,
                            Stock = 99
                        },
                        new
                        {
                            Id = 11,
                            ProductID = 11,
                            Stock = 90
                        },
                        new
                        {
                            Id = 12,
                            ProductID = 12,
                            Stock = 94
                        },
                        new
                        {
                            Id = 13,
                            ProductID = 13,
                            Stock = 77
                        },
                        new
                        {
                            Id = 14,
                            ProductID = 14,
                            Stock = 63
                        },
                        new
                        {
                            Id = 15,
                            ProductID = 15,
                            Stock = 58
                        },
                        new
                        {
                            Id = 16,
                            ProductID = 16,
                            Stock = 0
                        },
                        new
                        {
                            Id = 17,
                            ProductID = 17,
                            Stock = 62
                        },
                        new
                        {
                            Id = 18,
                            ProductID = 18,
                            Stock = 7
                        },
                        new
                        {
                            Id = 19,
                            ProductID = 19,
                            Stock = 52
                        },
                        new
                        {
                            Id = 20,
                            ProductID = 20,
                            Stock = 72
                        },
                        new
                        {
                            Id = 21,
                            ProductID = 21,
                            Stock = 63
                        },
                        new
                        {
                            Id = 22,
                            ProductID = 22,
                            Stock = 51
                        },
                        new
                        {
                            Id = 23,
                            ProductID = 23,
                            Stock = 16
                        },
                        new
                        {
                            Id = 24,
                            ProductID = 24,
                            Stock = 98
                        },
                        new
                        {
                            Id = 25,
                            ProductID = 25,
                            Stock = 31
                        },
                        new
                        {
                            Id = 26,
                            ProductID = 26,
                            Stock = 70
                        },
                        new
                        {
                            Id = 27,
                            ProductID = 27,
                            Stock = 0
                        },
                        new
                        {
                            Id = 28,
                            ProductID = 28,
                            Stock = 61
                        },
                        new
                        {
                            Id = 29,
                            ProductID = 29,
                            Stock = 28
                        },
                        new
                        {
                            Id = 30,
                            ProductID = 30,
                            Stock = 81
                        },
                        new
                        {
                            Id = 31,
                            ProductID = 31,
                            Stock = 0
                        },
                        new
                        {
                            Id = 32,
                            ProductID = 32,
                            Stock = 70
                        },
                        new
                        {
                            Id = 33,
                            ProductID = 33,
                            Stock = 15
                        },
                        new
                        {
                            Id = 34,
                            ProductID = 34,
                            Stock = 1
                        },
                        new
                        {
                            Id = 35,
                            ProductID = 35,
                            Stock = 49
                        },
                        new
                        {
                            Id = 36,
                            ProductID = 36,
                            Stock = 16
                        },
                        new
                        {
                            Id = 37,
                            ProductID = 37,
                            Stock = 91
                        },
                        new
                        {
                            Id = 38,
                            ProductID = 38,
                            Stock = 98
                        },
                        new
                        {
                            Id = 39,
                            ProductID = 39,
                            Stock = 69
                        },
                        new
                        {
                            Id = 40,
                            ProductID = 40,
                            Stock = 49
                        },
                        new
                        {
                            Id = 41,
                            ProductID = 41,
                            Stock = 59
                        },
                        new
                        {
                            Id = 42,
                            ProductID = 42,
                            Stock = 38
                        },
                        new
                        {
                            Id = 43,
                            ProductID = 43,
                            Stock = 75
                        },
                        new
                        {
                            Id = 44,
                            ProductID = 44,
                            Stock = 87
                        },
                        new
                        {
                            Id = 45,
                            ProductID = 45,
                            Stock = 90
                        },
                        new
                        {
                            Id = 46,
                            ProductID = 46,
                            Stock = 64
                        },
                        new
                        {
                            Id = 47,
                            ProductID = 47,
                            Stock = 5
                        },
                        new
                        {
                            Id = 48,
                            ProductID = 48,
                            Stock = 42
                        },
                        new
                        {
                            Id = 49,
                            ProductID = 49,
                            Stock = 1
                        },
                        new
                        {
                            Id = 50,
                            ProductID = 50,
                            Stock = 26
                        },
                        new
                        {
                            Id = 51,
                            ProductID = 51,
                            Stock = 88
                        },
                        new
                        {
                            Id = 52,
                            ProductID = 52,
                            Stock = 28
                        },
                        new
                        {
                            Id = 53,
                            ProductID = 53,
                            Stock = 59
                        },
                        new
                        {
                            Id = 54,
                            ProductID = 54,
                            Stock = 6
                        },
                        new
                        {
                            Id = 55,
                            ProductID = 55,
                            Stock = 71
                        },
                        new
                        {
                            Id = 56,
                            ProductID = 56,
                            Stock = 26
                        },
                        new
                        {
                            Id = 57,
                            ProductID = 57,
                            Stock = 13
                        },
                        new
                        {
                            Id = 58,
                            ProductID = 58,
                            Stock = 53
                        },
                        new
                        {
                            Id = 59,
                            ProductID = 59,
                            Stock = 64
                        },
                        new
                        {
                            Id = 60,
                            ProductID = 60,
                            Stock = 3
                        },
                        new
                        {
                            Id = 61,
                            ProductID = 61,
                            Stock = 39
                        },
                        new
                        {
                            Id = 62,
                            ProductID = 62,
                            Stock = 28
                        },
                        new
                        {
                            Id = 63,
                            ProductID = 63,
                            Stock = 72
                        },
                        new
                        {
                            Id = 64,
                            ProductID = 64,
                            Stock = 94
                        },
                        new
                        {
                            Id = 65,
                            ProductID = 65,
                            Stock = 99
                        },
                        new
                        {
                            Id = 66,
                            ProductID = 66,
                            Stock = 19
                        },
                        new
                        {
                            Id = 67,
                            ProductID = 67,
                            Stock = 79
                        },
                        new
                        {
                            Id = 68,
                            ProductID = 68,
                            Stock = 76
                        },
                        new
                        {
                            Id = 69,
                            ProductID = 69,
                            Stock = 14
                        },
                        new
                        {
                            Id = 70,
                            ProductID = 70,
                            Stock = 41
                        },
                        new
                        {
                            Id = 71,
                            ProductID = 71,
                            Stock = 9
                        },
                        new
                        {
                            Id = 72,
                            ProductID = 72,
                            Stock = 63
                        },
                        new
                        {
                            Id = 73,
                            ProductID = 73,
                            Stock = 37
                        },
                        new
                        {
                            Id = 74,
                            ProductID = 74,
                            Stock = 2
                        },
                        new
                        {
                            Id = 75,
                            ProductID = 75,
                            Stock = 13
                        },
                        new
                        {
                            Id = 76,
                            ProductID = 76,
                            Stock = 24
                        },
                        new
                        {
                            Id = 77,
                            ProductID = 77,
                            Stock = 76
                        },
                        new
                        {
                            Id = 78,
                            ProductID = 78,
                            Stock = 28
                        },
                        new
                        {
                            Id = 79,
                            ProductID = 79,
                            Stock = 7
                        },
                        new
                        {
                            Id = 80,
                            ProductID = 80,
                            Stock = 66
                        },
                        new
                        {
                            Id = 81,
                            ProductID = 81,
                            Stock = 65
                        },
                        new
                        {
                            Id = 82,
                            ProductID = 82,
                            Stock = 58
                        },
                        new
                        {
                            Id = 83,
                            ProductID = 83,
                            Stock = 60
                        },
                        new
                        {
                            Id = 84,
                            ProductID = 84,
                            Stock = 1
                        },
                        new
                        {
                            Id = 85,
                            ProductID = 85,
                            Stock = 93
                        },
                        new
                        {
                            Id = 86,
                            ProductID = 86,
                            Stock = 71
                        },
                        new
                        {
                            Id = 87,
                            ProductID = 87,
                            Stock = 11
                        },
                        new
                        {
                            Id = 88,
                            ProductID = 88,
                            Stock = 8
                        },
                        new
                        {
                            Id = 89,
                            ProductID = 89,
                            Stock = 29
                        },
                        new
                        {
                            Id = 90,
                            ProductID = 90,
                            Stock = 22
                        },
                        new
                        {
                            Id = 91,
                            ProductID = 91,
                            Stock = 3
                        },
                        new
                        {
                            Id = 92,
                            ProductID = 92,
                            Stock = 38
                        },
                        new
                        {
                            Id = 93,
                            ProductID = 93,
                            Stock = 34
                        },
                        new
                        {
                            Id = 94,
                            ProductID = 94,
                            Stock = 65
                        },
                        new
                        {
                            Id = 95,
                            ProductID = 95,
                            Stock = 10
                        },
                        new
                        {
                            Id = 96,
                            ProductID = 96,
                            Stock = 31
                        },
                        new
                        {
                            Id = 97,
                            ProductID = 97,
                            Stock = 66
                        },
                        new
                        {
                            Id = 98,
                            ProductID = 98,
                            Stock = 81
                        },
                        new
                        {
                            Id = 99,
                            ProductID = 99,
                            Stock = 88
                        },
                        new
                        {
                            Id = 100,
                            ProductID = 100,
                            Stock = 71
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
